name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: test
        run: yarn && yarn test
      - name: report
        uses: codecov/codecov-action@v1.1.1
        env:
          CI: true
